"rod_diameter"= 8
"rod_hole_thickness"= 4
"rod_radius"= "rod_diameter" / 2
"platter_diameter"= 320
"platter_radius"= "platter_diameter" / 2
"extruder_mount_hole_spacing"= 75
"arm_rod_spacing"= 40
"top_frame_rod_spacing"= "arm_rod_spacing" + 40
"motor_level_rod_spacing"= 15
"linear_bearing_diameter"= 15
"z_rod_spacing"= 75
"platter_rod_spacing"= 50
"rod_nut_thickness"= 6.5
"rod_nut_inscribed_diameter"= 13
"z_height"= 350
"gear_pitch"=2
"r_gear_teeth"= 450
"theta_gear_teeth"= 385
